### ISSUE TITLE
Add SVG Icons for buttons using Glyphicons

### ISSUE THREAD

**Issue by estebanborai** [learnFE/basic-counter#1]
Add glyhpicons to replace the current text of the counter buttons.

**Comment by GuillermoGarrido** [comment]
I'll do it later today.

**Comment by estebanborai** [comment]
Hi @GuillermoGarrido, I just assigned to you this issue!

**Comment by GuillermoGarrido** [comment]
The issue has been addressed: https://github.com/learnFE/basic-counter/pull/4
